import type { Medication } from "./types";

export function formatShareText(med: Medication): string {
  return `Knowdose Summary: ${med.name}

• What it does: ${med.overview}
• How to take it: ${med.howToTake.timing} — ${med.howToTake.withFood}
• Side effects: ${med.sideEffects.slice(0, 4).join(", ")}
• Warnings: ${med.warnings.slice(0, 3).join("; ")}

For general information only — not medical advice.
Generated by Knowdose`;
}
