import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/LegalPage";
import { ShieldCheck, Stethoscope, AlertCircle } from "lucide-react";

export const Route = createFileRoute("/medical-disclaimer")({
  head: () => ({
    meta: [
      { title: "Medical Disclaimer — MedMate" },
      { name: "description", content: "Important: this tool is for education only and does not provide medical diagnosis or treatment." },
      { property: "og:title", content: "Medical Disclaimer — MedMate" },
      { property: "og:description", content: "This tool is for education only and does not provide medical diagnosis or treatment." },
    ],
  }),
  component: DisclaimerPage,
});

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="font-display text-xl text-foreground mt-8 mb-2">{children}</h2>;
}

function DisclaimerPage() {
  return (
    <LegalPage
      title="Medical Disclaimer"
      intro="Please read this carefully before relying on anything from this service."
      updated="April 2026"
    >
      <div className="rounded-2xl border border-border/60 bg-primary-soft/40 p-5 flex gap-3">
        <ShieldCheck className="w-5 h-5 text-primary shrink-0 mt-0.5" />
        <p className="text-sm text-foreground/90">
          MedMate is an <strong>educational tool</strong>. It does not provide medical diagnosis, treatment, or personalised medical advice.
        </p>
      </div>

      <H2>Always speak to a professional</H2>
      <p>
        For anything about your health, your medication, your dosage, side effects, interactions, or whether to start, stop, or change a treatment — please speak to your <strong>doctor, pharmacist, or qualified healthcare professional</strong>. They know your full medical picture; we don't.
      </p>

      <H2>What this tool does</H2>
      <ul className="list-disc pl-5 space-y-1.5">
        <li>Explains medication information in plain language</li>
        <li>Summarises common side effects and how to take medicine</li>
        <li>Helps you prepare questions to ask a real professional</li>
      </ul>

      <H2>What this tool does NOT do</H2>
      <ul className="list-disc pl-5 space-y-1.5">
        <li>Diagnose any condition</li>
        <li>Prescribe or recommend medication for you specifically</li>
        <li>Replace a consultation with a doctor or pharmacist</li>
        <li>Handle emergencies of any kind</li>
      </ul>

      <div className="rounded-2xl border border-border/60 bg-card p-5 flex gap-3 mt-6">
        <AlertCircle className="w-5 h-5 text-warning shrink-0 mt-0.5" />
        <div className="text-sm text-foreground/90">
          <p className="font-medium">In an emergency</p>
          <p className="text-muted-foreground mt-1">
            If you think you or someone else is having a medical emergency, call your local emergency number immediately (999 in the UK, 112 in the EU, 911 in the US). Do not use this app.
          </p>
        </div>
      </div>

      <H2>Accuracy</H2>
      <p>
        Explanations are generated by AI from the input you provide and may be incomplete or contain mistakes. Always verify important information with your pharmacist or the official patient information leaflet that comes with your medicine.
      </p>

      <H2>One last thing</H2>
      <p className="inline-flex items-start gap-2">
        <Stethoscope className="w-4 h-4 mt-1 text-primary" />
        <span>We built this to help you feel more informed and confident — never to take the place of the people who actually care for you.</span>
      </p>
    </LegalPage>
  );
}
